#!/bin/bash
#
# Copyright © 2020 Filip Paskali
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
RED='\033[0;31m'
NC='\033[0m' # No Color
case $(pacmd list-sources | grep -A 11 0 | awk '/muted/ {print $2; exit}') in
    yes)
      echo "MIC MUTED"
      ;;
    no)
      echo ""
      ;;
esac
