[[profile]]
name = "docked"

[[profile.output]]
enable = true
search = ["m=0x095F", "s=", "v=BOE"]
mode = "2256x1504@59.999Hz"
position = "5732,1504"
scale = 1.69921875
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=BenQ RL2455", "s=13G07863SL0", "v=BNQ"]
mode = "1920x1080@60Hz"
position = "1907,0"
scale = 1.0
transform = "270"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=BenQ RL2455", "s=13G07872SL0", "v=BNQ"]
mode = "1920x1080@60Hz"
position = "5730,424"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=DELL S2721QS", "s=1M1JZY3", "v=Dell Inc."]
mode = "3840x2160@30Hz"
position = "2987,217"
scale = 1.3984375
transform = "normal"
adaptive_sync = false


[[profile]]
name = "undocked"

[[profile.output]]
enable = true
search = ["m=0x095F", "s=", "v=BOE"]
mode = "2256x1504@59.999Hz"
position = "3584,1760"
scale = 1.69921875
transform = "normal"
adaptive_sync = false

